env:
  browser: true
  es6: true
  node: true
extends:
  - airbnb-base
  - plugin:jest/recommended
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2018
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  default-case: off
  guard-for-in: off
  max-len: off
  no-restricted-syntax: off
