env:
  browser: true
  es2021: true
  node: true
  jest/globals: true
extends:
  - airbnb-base
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
  - jest
rules:
  default-case: off
  import/extensions: off
  import/no-unresolved: off
  guard-for-in: off
  max-len: off
  no-restricted-syntax: off
  no-unused-vars: off
  object-curly-newline: off
  '@typescript-eslint/no-unused-vars': [error]
